### ISSUE TITLE
Bonus Bits History + Bitz Balance on headers to also include bonus

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/explorer-dapp#462]
We now have the ability to give bonus "bitz" XP to an (mvx/sol)address + data nft identity . Bonus bitz are sent by an "admin" as a reward for a user doing certain "protocol" level tasks. e.g. testing the bridge.

Firstly, an admin can send a (mvx/sol)address + data nft identity some bonus bitz using a private endpoint. These bonuz bits gets stored separately in the database

### **Task 1:**
In both the solana and mvx bitz xp apps, the following UI changes need to be made. 

1. A new section like so should appear 
![image](https://github.com/Itheum/explorer-dapp/assets/743169/886bd11f-f1a3-4e97-8105-2ea605668d62)

2. If the user has "0" bonus bitz, then instead of a empty table in the body appearing, it should say:  "No Bonus BiTz received yet"

3. You can get the data for the user from here:
https://api.itheumcloud-stg.com/datadexapi/xpGamePrivate/bonusHistoryForAddr?addr=erd1eweqykxcrhh5nps4fzktu9eftf7rxpa8xdfkypwz0k4huhl0s04sa6tqyd

[Note that you have to set the fwd-tokenid header as well or it wont work]. e.g. 
<img width="602" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/328c8efd-7823-42dd-ab32-04cf19edfd9a">

4. You only make the API call AND show the UI section -- IF THERE USER IS LOGGED IN. 

### **Task 2:**
The BiTz Balance we show on top for all 3 sections: MvX BiTz App, Solana BiTz App, Data DEX header -- needs to now take into account the "bonus bitz" balance and adjust before showing to the user. How can you do this? 

<img width="124" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/6b651ecd-1996-41db-8418-b02c7ecdfac2">

The BiTz data stream now returns `bitsBonusSum` property like so, (also note it has a bitsGivenSum property)
<img width="244" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/bbbb69de-963d-48f1-aedd-cd48679383ec">

The value here, should be the ((bitsScoreBeforePlay or bitsScoreAfterPlay) + bitsBonusSum) - bitsGivenSum
<img width="124" alt="image" src="https://github.com/Itheum/explorer-dapp/assets/743169/6b651ecd-1996-41db-8418-b02c7ecdfac2">

**Comment by damienen** [comment]
- [ ] Task 1 SOL Get Bitz
- [ ] Task 1 Explorer
- [ ] Task 1 Data Dex
- [ ] Task 2 Data Dex
- [ ] Task 2 Explorer
- [ ] Task 2 SOL Get BItz
